services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: wavestore-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./wavestore-backend-light-version:/var/www/html
      - frontend-dist:/usr/share/nginx/html
    depends_on:
      - laravel-app
      - frontend-prod
    networks:
      - app-network

  frontend-prod:
    build:
      context: ./wavestore-light-version-front
      dockerfile: Dockerfile
    container_name: wavestore-website-prod
    volumes:
      - frontend-dist:/app/dist
    networks:
      - app-network

  laravel-app:
    build:
      context: ./wavestore-backend-light-version
      dockerfile: Dockerfile
    container_name: wavestore-laravel-prod
    env_file:
      - ./wavestore-backend-light-version/.env.docker
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: wavestore-mysql-prod
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=desinmix_php
    volumes:
      - mysql-data-prod:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data-prod:
  frontend-dist: